sudo: required
services:
  - docker

before_install:
  - docker build -t bschelfh/docker-react -f Dockerfile.dev .

script:
        #  - docker run bschelfh/docker-react npm run test -- --coverage
  - docker run -e CI=true bschelfh/docker-react npm run test
